version: '{build}'
environment:
  COVERALLSAPIKEY:
    secure: hpY/hRt3Qq8aowHS8nC1ulEZztGGpv6Yww56OS3eiAwB9tUFcbUbisT3S0PrfFpU
build_script:
- ps: .\build.ps1 -target=CoveragePublish -configuration=Debug "-coverallsApiKey=$env:COVERALLSAPIKEY"
test: off
